# -*- coding: utf-8 -*-
"""Day17.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HcepcXNLFoXUYo2rWQgeRM8ZJF-jprHz
"""

題目 : 

在速度較慢的時候，可以先從哪邊開始檢查？
可以先檢查欄位的型態，使用降級的檔案可以增加檔案的讀取速率

資料過大時應採取什麼方式讓記憶體占用量下降？
可將整數型態 int 改成 uint 減少記憶體佔用空間