# -*- coding: utf-8 -*-
"""Day24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12S7fLGzcQ4FI2zGfbLupvN_5BoCEjbio
"""

!pip install geos
!pip install pyproj
!apt-get install -q libgeos-3.5.0
!apt-get install -q libgeos-dev
!pip install -q https://github.com/matplotlib/basemap/archive/master.zip
!pip install -q pyproj==1.9.6

# 導入開發套件
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

# 新建地圖
map = Basemap()
#Basemap有很多屬性，這里全都使用默認参數

# 畫圖
map.drawcoastlines()

# 顯示结果
plt.show()

# 存储结果
# plt.savefig('test.png')

from google.colab import drive
drive.mount('/content/drive')

# Basemap支援的投影類型：
import mpl_toolkits.basemap

# print(mpl_toolkits.basemap.supported_projections)

# Projections 投影是一個重要基礎
# 更改投影方式
map = Basemap(projection = 'ortho', lat_0 = 0, lon_0 = 0)
#’ortho’指正射投影，後面两個参數是设置中心點


# 给整個地圖上藍色
map.drawmapboundary(fill_color = 'aqua')

# 给陸地塗上珊瑚色，湖泊塗上藍色
map.fillcontinents(color = 'coral', lake_color = 'aqua')

# 畫圖
map.drawcoastlines()

# 顯示结果
plt.show()