# -*- coding: utf-8 -*-
"""Day20.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZ4FKU1gD1zCfup7fZaIl9-rTd-ij4ZR
"""

# 1.繪製模型殘差 圖型
import numpy as np
import seaborn as sns

#設定圖形樣式 - whitegrid
# use sns.set

# 利用 NUMPY 去建立資料集
# np.random.RandomState 設定數學式
'''
x = rs.normal(2, 1, 75)
y = 2 + 1.5 * x + rs.normal(0, 2, 75)
'''

# 畫圖
# sns.residplot

繪製單變數分佈:快速檢視海出生單變數分佈的最便捷方式是distplot() 函數。
默認情況下,這將繪製直方圖並適合內核密度估計值(KDE)。

# 2.1使用distplot()使用簡單的規則來正確猜測預設情況下正確的數位,但嘗試更多或更少的 bin 可能會顯示資料中的其他特徵: 
# 2.2有無kde對圖形分布的影響